name: Check Generated

on:
    push:
        paths:
            - 'logic/**/main/**/*Assertions.kt'
    pull_request:
        paths:
            - 'logic/**/main/**/*Assertions.kt'

jobs:
    build:
        runs-on: windows-latest
        strategy:
            fail-fast: true
            matrix:
                java_version: [9, 10, 11, 12, 13, 14]
        steps:
            -   uses: actions/checkout@v2
            -   name: "Set up JDK ${{ matrix.java_version }}"
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java_version }}

            -   name: check generateLogic committed
                run: ./gradle/scripts/check-generateLogic-committed.sh
                shell: bash
